include $(top_srcdir)/Makefile.common.in
lib_LTLIBRARIES=libServerCenter.la
libServerCenter_la_INCLUDES = -I libServerCenter_la_SOURCES = 
libServerCenter_la_LIBADD = 
libServerCenter_la_DEFINES = 
libServerCenter_la_CXXFLAGS = $(libServerCenter_la_DEFINES) $(libServerCenter_la_INCLUDES)
libServerCenter_la_CFLAGS = $(libServerCenter_la_DEFINES) $(libServerCenter_la_INCLUDES)
